package model;
// Generated 10 ene 2024 18:09:09 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Juegos generated by hbm2java
 */
public class Juegos implements java.io.Serializable {

  private Integer idJuego;
  private String ISBN;
  private Usuarios usuarios;
  private String nombreJuego;
  private String plataforma;
  private double precio;
  private Set ventases = new HashSet(0);

  public Juegos() {
  }

  public Juegos(Usuarios usuarios,String ISBN, String nombreJuego, String plataforma, double precio, Set ventases) {
    this.usuarios = usuarios;
    this.ISBN = ISBN;
    this.nombreJuego = nombreJuego;
    this.plataforma = plataforma;
    this.precio = precio;
    this.ventases = ventases;
  }

  public Juegos(Juegos idjuego) {
  }

  public Integer getIdJuego() {
    return this.idJuego;
  }

  public void setIdJuego(Integer idJuego) {
    this.idJuego = idJuego;
  }

  public Usuarios getUsuarios() {
    return this.usuarios;
  }

  public void setUsuarios(Usuarios usuarios) {
    this.usuarios = usuarios;
  }

  public String getNombreJuego() {
    return this.nombreJuego;
  }

  public void setNombreJuego(String nombreJuego) {
    this.nombreJuego = nombreJuego;
  }

  public String getPlataforma() {
    return this.plataforma;
  }

  public void setPlataforma(String plataforma) {
    this.plataforma = plataforma;
  }

  public double getPrecio() {
    return this.precio;
  }

  public void setPrecio(double precio) {
    this.precio = precio;
  }

  public Set getVentases() {
    return this.ventases;
  }

  public void setVentases(Set ventases) {
    this.ventases = ventases;
  }

    public String getISBN() {
        return ISBN;
    }

    public void setISBN(String ISBN) {
        this.ISBN = ISBN;
    }

    @Override
    public String toString() {
        return "Juegos{" + "idJuego=" + idJuego + ", ISBN=" + ISBN + ", usuarios=" + usuarios + ", nombreJuego=" + nombreJuego + ", plataforma=" + plataforma + ", precio=" + precio + ", ventases=" + ventases + '}';
    }

  
    

  
}
