/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.controladorLoggin;
import com.formdev.flatlaf.intellijthemes.FlatLightFlatIJTheme;
import java.awt.Color;
import java.awt.Cursor;
import javax.swing.JOptionPane;
import model.Usuarios;

/**
 *Este frame contiene los elementos para inciar sesion, ir a registrarse y recuperar la contraseña.
 * Se compone de dos botones, dos jTExtField y un panel interior con un texto para ir a otro frame.
 * Al introducir correctamente las credenciales se cierra este frame y te lleva al principal, si las credenciales son incorrectas
 * se avisa al usuario
 * @author Diego Sanchez Gandara
 */
public class Loggin extends javax.swing.JFrame {
    /**
     * Se llama a los controladores y el resto de frames para hacer los cambios y llamar a los metodos.
     */
    private Registrarse regis;
    private RecuperarContrasena rec;
    private controladorLoggin clg = new controladorLoggin();
    private VentanaPrincipal ve;
    private Principal p1;
    /**
     * Aqui se introduce todo el diseño de flatlaf. Redondeo de botones, tooltip y placeholder.
     * Creates new form Loggin
     */
    public Loggin() {
        initComponents();
        //diseños de flatlaf
        botonIniciarSesion.putClientProperty( "JButton.buttonType" , "roundRect" );
        botonRegistrarse.putClientProperty( "JButton.buttonType" , "roundRect" );
        Usuario.putClientProperty("JTextField.placeholderText", "ingrese el email de usuario");
        Contrasena.putClientProperty("JTextField.placeholderText", "***********");
        botonIniciarSesion.setToolTipText("Boton para iniciar sesion");
        Usuario.setToolTipText("Ingrese aqui su email");
        Contrasena.setToolTipText("Ingrese aqui su contraseña");
        botonOlvidada.setToolTipText("Boton para recuperar la contraseña");
        botonRegistrarse.setToolTipText("Boton para registrarse");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        panelInterior = new javax.swing.JPanel();
        Usuario = new javax.swing.JTextField();
        Contrasena = new javax.swing.JPasswordField();
        botonIniciarSesion = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        botonRegistrarse = new javax.swing.JButton();
        fondoCont = new javax.swing.JPanel();
        botonOlvidada = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(0, 0, 0));

        panelInterior.setBackground(new java.awt.Color(248, 248, 248));

        Usuario.setForeground(new java.awt.Color(102, 102, 102));
        Usuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        Contrasena.setForeground(new java.awt.Color(102, 102, 102));
        Contrasena.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        botonIniciarSesion.setBackground(new java.awt.Color(0, 0, 0));
        botonIniciarSesion.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        botonIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonIniciarSesion.setText("Iniciar Sesion");
        botonIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIniciarSesionMouseExited(evt);
            }
        });
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(244, 40, 84));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("_________");

        jLabel4.setForeground(new java.awt.Color(244, 40, 84));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("_________");

        jLabel5.setForeground(new java.awt.Color(244, 40, 84));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("No tienes cuenta ?");

        botonRegistrarse.setBackground(new java.awt.Color(0, 0, 0));
        botonRegistrarse.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 14)); // NOI18N
        botonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        botonRegistrarse.setText("Registrarse");
        botonRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRegistrarseMouseExited(evt);
            }
        });
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        fondoCont.setBackground(new java.awt.Color(248, 248, 248));
        fondoCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoContMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fondoContMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fondoContMouseExited(evt);
            }
        });

        botonOlvidada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        botonOlvidada.setText("Olvidaste tu contraseña ?");
        botonOlvidada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonOlvidadaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonOlvidadaMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout fondoContLayout = new javax.swing.GroupLayout(fondoCont);
        fondoCont.setLayout(fondoContLayout);
        fondoContLayout.setHorizontalGroup(
            fondoContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoContLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(botonOlvidada, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
        fondoContLayout.setVerticalGroup(
            fondoContLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoContLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(botonOlvidada)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInteriorLayout = new javax.swing.GroupLayout(panelInterior);
        panelInterior.setLayout(panelInteriorLayout);
        panelInteriorLayout.setHorizontalGroup(
            panelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(fondoCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelInteriorLayout.setVerticalGroup(
            panelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInteriorLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(fondoCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelInteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Eras Bold ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIO SESION");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/charmander 1.png"))); // NOI18N

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
            .addComponent(panelInterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel2))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(panelInterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 375, 667));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este metodo hace que al pulsar el texto te lleve al frame para crear un nuevo usuario y cierra este
     * @param evt 
     */
    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        regis = new Registrarse();
        regis.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRegistrarseActionPerformed

   /**
    * este metodo llama al controlador del loggin.
    * Primero comprueba que los textField no esten vacios, si lo estan avisa al usuario.
    * Si no estan vacios recoge en variables los datos introducidos y comprueba que el email exista. Si el mail no existe se informa del error,
    * si el email existe se recoge la contraseña del usuario a traves del mail y se valida. Si es incorrecta avisa del error sino permite iniciar sesion.
    * @param evt 
    */
    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        if (Usuario.getText().isEmpty() || Contrasena.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null, "Introduzca todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            String usu = Usuario.getText();
            String cont = Contrasena.getText();
        try {
            boolean comp2 = clg.comprobarMail(usu);
            if (comp2) {
                String contrasenaAlmacenada = clg.obtenerContrasenaDeUsuario(usu);
                boolean comprueba = clg.verificarContrasena(cont, contrasenaAlmacenada);
                if (comprueba) {
                    dispose();
                    // para ir a la otra ventana
                    VentanaPrincipal p1 = new VentanaPrincipal();
                    // cerrar o esconder antes de abrir principal
                    p1.setVisible(true);
                }else{
                     JOptionPane.showMessageDialog(rootPane, "Contraseña no válida", "Error en el inicio de sesión", JOptionPane.ERROR_MESSAGE);
                     Contrasena.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(rootPane, "Email incorrecto", "Error en el inicio de sesión", JOptionPane.ERROR_MESSAGE);
                Usuario.setText("");
            }
            /*boolean comp2 = clg.comprobarMail(usu);
            // Obtener la contraseña almacenada del usuario
            String contrasenaAlmacenada = clg.obtenerContrasenaDeUsuario(usu);
            // Verificar si la contraseña almacenada coincide con la ingresada por el usuario
            System.out.println(contrasenaAlmacenada);
            System.out.println(usu);
            boolean comprueba = clg.verificarContrasena(cont, contrasenaAlmacenada);
            
            System.out.println(comp2);
            if (!comprueba) {
                JOptionPane.showMessageDialog(rootPane, "Contraseña no válida", "Error en el inicio de sesión", JOptionPane.ERROR_MESSAGE);
            }else if(!comp2){
                JOptionPane.showMessageDialog(rootPane, "Email incorrecto", "Error en el inicio de sesión", JOptionPane.ERROR_MESSAGE);
            }else{
                dispose();
                // para ir a la otra ventana
                VentanaPrincipal p1 = new VentanaPrincipal();
                // cerrar o esconder antes de abrir principal
                p1.setVisible(true);
            }*/
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
       
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    /**
     * este metodo hace que al pulsar el panel interior te mande al frame de recuperar contraseña
     * @param evt 
     */
    private void fondoContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoContMouseClicked
        rec = new RecuperarContrasena();
        rec.setVisible(true);
        dispose();
    }//GEN-LAST:event_fondoContMouseClicked

    /**
     * este metodo hace que al introducir el mouse en el boton el cursor cambie a una mano para indicar que se puede pulsar
     * @param evt 
     */
    private void fondoContMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoContMouseEntered
        setCursor(HAND_CURSOR);
        
    }//GEN-LAST:event_fondoContMouseEntered
    /**
     * este metodo hace que al introducir el mouse en el boton el cursor cambie a una mano para indicar que se puede pulsar
     * @param evt 
     */
    private void botonIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseEntered
        setCursor(HAND_CURSOR);
        botonIniciarSesion.setBackground(new Color(75, 72, 71));
    }//GEN-LAST:event_botonIniciarSesionMouseEntered
    /**
     * este metodo hace que al introducir el mouse en el boton el cursor cambie a una mano para indicar que se puede pulsar
     * @param evt 
     */
    private void botonRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseEntered
        setCursor(HAND_CURSOR);
        botonRegistrarse.setBackground(new Color(75, 72, 71));
        
    }//GEN-LAST:event_botonRegistrarseMouseEntered
    /**
     * este metodo hace que al sacar el mouse del boton vuelva a su forma normal
     * @param evt 
     */
    private void fondoContMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoContMouseExited
        setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_fondoContMouseExited
    /**
     * este metodo hace que al introducir el mouse en el boton el cursor cambie a una mano para indicar que se puede pulsar
     * @param evt 
     */
    private void botonOlvidadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOlvidadaMouseEntered
        setCursor(HAND_CURSOR);
    }//GEN-LAST:event_botonOlvidadaMouseEntered
    /**
     * este metodo hace que al sacar el mouse del boton vuelva a su forma normal y vuelva a su color
     * @param evt 
     */
    private void botonIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIniciarSesionMouseExited
        setCursor(Cursor.getDefaultCursor());
         botonIniciarSesion.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_botonIniciarSesionMouseExited
    /**
     * este metodo hace que al sacar el mouse del boton vuelva a su forma normal y vuelva a su color
     * @param evt 
     */
    private void botonRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRegistrarseMouseExited
         botonRegistrarse.setBackground(new Color(0, 0, 0));
         setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_botonRegistrarseMouseExited
    /**
     * este metodo hace que al pulsar el texto te lleve al frame de recuperar contraseña
     * @param evt 
     */
    private void botonOlvidadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonOlvidadaMouseClicked
        rec = new RecuperarContrasena();
        rec.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonOlvidadaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loggin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //llamamos al tema de flatlaf
        FlatLightFlatIJTheme.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loggin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Contrasena;
    private javax.swing.JTextField Usuario;
    private javax.swing.JButton botonIniciarSesion;
    private javax.swing.JLabel botonOlvidada;
    private javax.swing.JButton botonRegistrarse;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel fondoCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelInterior;
    // End of variables declaration//GEN-END:variables
}
