/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorListar;
import Controlador.Render;
import Controlador.Render;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ventas;

/**
 *
 * @author Diego Sanchez Gandara
 */
public class panelListar extends javax.swing.JPanel {
    //declaramos un modelo para la tabla y llamamos al controlador
    DefaultTableModel modelo = new DefaultTableModel();
    private ControladorListar cl = new ControladorListar();
    private Render r = new Render();
    /**
     * Creates new form panelListar
     */
    public panelListar() {
        initComponents();
        //funciones de flatlaf
        botonRefrescar.putClientProperty( "JButton.buttonType" , "roundRect" );
        botonRefrescar.setToolTipText("Boton para refrescar la tabla");
        botonBorrar.setToolTipText("Boton para eliminar un registro");
        Object cellValue = tablaFinal.getValueAt(tablaFinal.getSelectedRow(), 5);
        r.getTableCellRendererComponent(tablaFinal, cellValue, true, true, tablaFinal.getSelectedRow(), 5);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRefrescar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        botonVer = new javax.swing.JButton();

        setBackground(new java.awt.Color(6, 2, 221));

        botonRefrescar.setBackground(new java.awt.Color(0, 0, 0));
        botonRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        botonRefrescar.setText("Refresh");
        botonRefrescar.setToolTipText("");
        botonRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRefrescarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRefrescarMouseExited(evt);
            }
        });
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });

        botonBorrar.setBackground(new java.awt.Color(6, 2, 221));
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/papelera .png"))); // NOI18N
        botonBorrar.setToolTipText("boton para eliminar registro");
        botonBorrar.setBorderPainted(false);
        botonBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonBorrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonBorrarMouseExited(evt);
            }
        });

        tablaFinal.setBackground(new java.awt.Color(255, 255, 255));
        tablaFinal.setForeground(new java.awt.Color(0, 0, 0));
        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Juego", "Plataforma", "Precio", "Cliente", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFinal.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaFinal);
        tablaFinal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        botonVer.setBackground(new java.awt.Color(0, 0, 0));
        botonVer.setForeground(new java.awt.Color(255, 255, 255));
        botonVer.setText("Mas informacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(botonVer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    //boton para mostrar los datos en la tabla
    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed
       modelo = cl.recogerDatos(tablaFinal);
       tablaFinal.setModel(modelo);
       
    }//GEN-LAST:event_botonRefrescarActionPerformed

    //metodos para los holder de los botones y el cursor, al entrar en el boton cambia el brillo del boton y el cursor se vuelve una mano y al salir vuelva a la normalidad 
    private void botonRefrescarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRefrescarMouseEntered
        botonRefrescar.setBackground(new Color(75, 72, 71));
    }//GEN-LAST:event_botonRefrescarMouseEntered

    private void botonRefrescarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRefrescarMouseExited
        botonRefrescar.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_botonRefrescarMouseExited

    private void botonBorrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseEntered
        botonBorrar.setBackground(new Color(75, 72, 71));
    }//GEN-LAST:event_botonBorrarMouseEntered

    private void botonBorrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonBorrarMouseExited
         botonBorrar.setBackground(new Color(6,2,221));
    }//GEN-LAST:event_botonBorrarMouseExited
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JButton botonVer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFinal;
    // End of variables declaration//GEN-END:variables
}
