/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorListar;
import Controlador.Render;
import Controlador.Render;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ventas;

/**
 *Este panel lista los datos de los juegos y los clientes que estan envueltos en una venta y nos permite borrar la venta de ellos.
 * @author Diego Sanchez Gandara
 */

public class panelListar extends javax.swing.JPanel {
    /**
     * Llamamos la modelo de la tabla y al controlador de el panel.
     */
    
    DefaultTableModel modelo = new DefaultTableModel();
    private ControladorListar cl = new ControladorListar();
    
    /**
     * Creates new form panelListar
     */
    public panelListar() {
        initComponents();
       /**
        * Diseño de botones y tooltip
        */
        botonRefrescar.putClientProperty( "JButton.buttonType" , "roundRect" );
        botonRefrescar.setToolTipText("Boton para refrescar la tabla");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonRefrescar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFinal = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(6, 2, 221));

        botonRefrescar.setBackground(new java.awt.Color(0, 0, 0));
        botonRefrescar.setForeground(new java.awt.Color(255, 255, 255));
        botonRefrescar.setText("Refresh");
        botonRefrescar.setToolTipText("");
        botonRefrescar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonRefrescar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonRefrescarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonRefrescarMouseExited(evt);
            }
        });
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });

        tablaFinal.setBackground(new java.awt.Color(255, 255, 255));
        tablaFinal.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        tablaFinal.setForeground(new java.awt.Color(0, 0, 0));
        tablaFinal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Juego", "Plataforma", "Precio", "Cliente", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaFinal.setColumnSelectionAllowed(true);
        tablaFinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaFinalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaFinal);
        tablaFinal.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mando.jpg"))); // NOI18N
        jLabel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(botonRefrescar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Este evento llama al modelo para la tabla 
     * @param evt 
     */
    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed
       modelo = cl.recogerDatos(tablaFinal);
       cl.isCellEditable(tablaFinal.getRowCount(), tablaFinal.getColumnCount());
       tablaFinal.setModel(modelo);
       
    }//GEN-LAST:event_botonRefrescarActionPerformed

   /**
    * este evento refresca la informacion de la tabla
    * @param evt 
    */
    private void botonRefrescarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRefrescarMouseEntered
        botonRefrescar.setBackground(new Color(75, 72, 71));
    }//GEN-LAST:event_botonRefrescarMouseEntered

    /**
     * Este evento cambia el hover del boton
     * @param evt 
     */
    private void botonRefrescarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonRefrescarMouseExited
        botonRefrescar.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_botonRefrescarMouseExited

    /**
     * este evento sirve para el evento del boton en la tabla, para obtener el valor.
     * @param evt 
     */
    private void tablaFinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaFinalMouseClicked
        int column = tablaFinal.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tablaFinal.getRowHeight();
        if (row < tablaFinal.getRowCount() && row >= 0 && column < tablaFinal.getColumnCount() && column >= 0) {
            Object value = tablaFinal.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton)value).doClick();
                JButton boton = (JButton) value;
            }
        }
    }//GEN-LAST:event_tablaFinalMouseClicked

    private void jLabel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1AncestorAdded
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaFinal;
    // End of variables declaration//GEN-END:variables
}
