/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ControladorIncluirVenta;
import java.awt.Color;
import java.time.LocalDate;
import java.sql.Date;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import model.Clientes;
import model.Juegos;


/**
 *Este panel introduce datos de juegos, clientes y ventas en la base de datos.
 * @author Diego Sanchez Gandara
 */
public class panelIntroducir extends javax.swing.JPanel {
    /**
     * Llamamos a su controlador y a las clases clientes y juegos.
     */
    private Controlador.ControladorIncluirVenta civ = new ControladorIncluirVenta();
    private Juegos j = new Juegos();
    private Clientes c = new Clientes();
    
    /**
     * Estilos de fuente y demas.
     */
    public panelIntroducir() {
        initComponents();
        //estilos de fuente
        jLabel1.putClientProperty("FlatLaf.style", "font: $h2.font");
        jLabelT.putClientProperty("FlatLaf.style", "font: $h2.font");
        jLabel2.putClientProperty("FlatLaf.style", "font: $h2.font");
        jLabel3.putClientProperty("FlatLaf.style", "font: $h2.font");
        jLabel4.putClientProperty("FlatLaf.style", "font: $h2.font");
        
        botonIntroducir.putClientProperty( "JButton.buttonType" , "roundRect" );
        ISBNJuego.putClientProperty( "JComponent.roundRect", true );
        nombreJuego.putClientProperty( "JComponent.roundRect", true );
        plataforma.putClientProperty( "JComponent.roundRect", true );
        precio.putClientProperty( "JComponent.roundRect", true );
        clienteNombre.putClientProperty( "JComponent.roundRect", true );
        
        ISBNJuego.putClientProperty( "JTextField.placeholderText" , "ingrese el ISBN del juego" );
        nombreJuego.putClientProperty( "JTextField.placeholderText" , "ingrese el nombre del juego" );
        plataforma.putClientProperty( "JTextField.placeholderText" , "ingrese la plataforma");
        precio.putClientProperty( "JTextField.placeholderText" , "ingrese el precio" );
        clienteNombre.putClientProperty( "JTextField.placeholderText" , "ingrese el cliente" );
        nombreJuego.setToolTipText("Introduzca el nombre del juego");
        plataforma.setToolTipText("Introduzca la plataforma del juego");
        precio.setToolTipText("Introduzca el precio del juego");
        clienteNombre.setToolTipText("Introduzca el nombre del cliente");
        botonIntroducir.setToolTipText("Boton para introducir los datos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreJuego = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        plataforma = new javax.swing.JTextField();
        precio = new javax.swing.JTextField();
        clienteNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        botonIntroducir = new javax.swing.JButton();
        jLabelT = new javax.swing.JLabel();
        ISBNJuego = new javax.swing.JTextField();

        setBackground(new java.awt.Color(6, 2, 221));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ISBN:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Plataforma:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Precio:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cliente:");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/paimon 1.png"))); // NOI18N

        botonIntroducir.setBackground(new java.awt.Color(0, 0, 0));
        botonIntroducir.setForeground(new java.awt.Color(255, 255, 255));
        botonIntroducir.setText("INTRODUCIR");
        botonIntroducir.setToolTipText("");
        botonIntroducir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIntroducir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonIntroducirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonIntroducirMouseExited(evt);
            }
        });
        botonIntroducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIntroducirActionPerformed(evt);
            }
        });

        jLabelT.setForeground(new java.awt.Color(0, 0, 0));
        jLabelT.setText("Titulo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ISBNJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(botonIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel5))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ISBNJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(nombreJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(plataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(botonIntroducir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(clienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * este boton introduce datos en la base de datos. Si ninguno de los datos existe lo crea todo, si existe el isbn del juego 
     * indica que no se puede repetir, si el cliente ya existe solo introduce la venta con los datos del juego y recupera los 
     * datos del cliente de la tabla. No se pueden introducir las ventas totalmento iguales.
     * @param evt 
     */
    private void botonIntroducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIntroducirActionPerformed
        if (nombreJuego.getText().isEmpty() || plataforma.getText().isEmpty() || precio.getText().isEmpty() || clienteNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Introduzca todos los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }else{
           try {
           
            String isb = ISBNJuego.getText();
            String titulo = nombreJuego.getText();
            String plat = plataforma.getText();
            double perc = Double.parseDouble(precio.getText());
            String client = clienteNombre.getText();
            LocalDate fecha = LocalDate.now();
            Date date = Date.valueOf(fecha);
            boolean compClie = civ.comprobarCliente(client);
            boolean com = civ.comprobarRepetidos(titulo, plat, perc, client);
           
            if (com == true) {
                JOptionPane.showMessageDialog(null, "La venta ya está registrada", "Error", JOptionPane.INFORMATION_MESSAGE);
                ISBNJuego.setText("");
                nombreJuego.setText("");
                plataforma.setText("");
                precio.setText("");
                clienteNombre.setText("");
            
            } else {
                boolean comI = civ.comprobarISBN(isb);
                if (comI) {
                    JOptionPane.showMessageDialog(null, "No se puede repetir el ISBN", "Error", JOptionPane.ERROR_MESSAGE);
                    ISBNJuego.setText("");
                    nombreJuego.setText("");
                    plataforma.setText("");
                    precio.setText("");
                    clienteNombre.setText("");
                }else if(compClie){
                    int idC = civ.obtenerIdCliente(client);
                    civ.introducirJuego(isb, titulo, plat, perc);
                    civ.registrarVenta2(titulo, idC, perc, date);
                    JOptionPane.showMessageDialog(null, "Venta registrada con exito", "Bien", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    civ.introducirJuego(isb, titulo, plat, perc);
                    civ.introducirCliente(client);
                    civ.registrarVenta(titulo, client, perc, date);
                    JOptionPane.showMessageDialog(null, "Venta registrada con exito", "Bien", JOptionPane.INFORMATION_MESSAGE);
                    ISBNJuego.setText("");
                    nombreJuego.setText("");
                    plataforma.setText("");
                    precio.setText("");
                    clienteNombre.setText("");
                }
            }
            
        } catch (ClassCastException e) {
           e.printStackTrace();
        } 
        }
        
    }//GEN-LAST:event_botonIntroducirActionPerformed
    /**
     * estos botones cambian el hover de los botones.
     * @param evt 
     */
    private void botonIntroducirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIntroducirMouseEntered
        botonIntroducir.setBackground(new Color(75, 72, 71));
    }//GEN-LAST:event_botonIntroducirMouseEntered

    private void botonIntroducirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIntroducirMouseExited
        botonIntroducir.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_botonIntroducirMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ISBNJuego;
    private javax.swing.JButton botonIntroducir;
    private javax.swing.JTextField clienteNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelT;
    private javax.swing.JTextField nombreJuego;
    private javax.swing.JTextField plataforma;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables
}
