package model;
// Generated 10 ene 2024 18:09:09 by Hibernate Tools 6.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private Integer id;
	private String username;
	private String contrasena;
	private String email;
	private Set juegoses = new HashSet(0);
	private Set clienteses = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String username, String contrasena, String email, Set juegoses, Set clienteses) {
		this.username = username;
		this.contrasena = contrasena;
		this.email = email;
		this.juegoses = juegoses;
		this.clienteses = clienteses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getContrasena() {
		return this.contrasena;
	}

	public void setContrasena(String contrasena) {
		this.contrasena = contrasena;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getJuegoses() {
		return this.juegoses;
	}

	public void setJuegoses(Set juegoses) {
		this.juegoses = juegoses;
	}

	public Set getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set clienteses) {
		this.clienteses = clienteses;
	}

}
